export const quizData1 = [
  {
    question: "In which world cup cricket final, Australia beat England",
    a: "1983, Lord’s – England",
    b: "1987, Kolkata – India",
    c: "1992, Melbourne – Australia",
    d: "1996, Lahore – Pakistan ",
    correct: "b",
  },
  {
    question: "Who won the first ever Cricket World Cup in 1975?",
    a: "Australia",
    b: "England",
    c: "India",
    d: "West Indies",
    correct: "d",
  },
  {
    question: "Which of the following terms is used in game of Cricket",
    a: "Love",
    b: "Scoop",
    c: "LBW",
    d: "Tee",
    correct: "c",
  },
  {
    question:
      "In which city was the Sri Lankan cricket team attacked in March 2009",
    a: "Dhaka   ",
    b: "Lahore  ",
    c: "Kabul  ",
    d: "Colombo",
    correct: "b",
  },
  {
    question: "Who did England beat in the final of the 2019 Cricket World Cup",
    a: "Australia",
    b: "India",
    c: "New Zealand",
    d: "South Africa",
    correct: "c",
  },
  {
    question: "Which fast bowler has taken the most test wickets",
    a: "Stuart Broad",
    b: "Dale Steyn",
    c: "Glenn McGrath",
    d: "James Anderson",
    correct: "d",
  },
  {
    question: "The distance between the popping crease and the bowling crease is",
    a: "5 Feet",
    b: "6 Feet",
    c: "4 Feet",
    d: "6 Feet",
    correct: "c",
  },
  {
    question: "What was the official name of the first World Cup",
    a: "ICC World Cup",
    b: "ICC Trophy",
    c: "ICC Champion",
    d: "Prudential World Cup",
    correct: "d",
  },
  {
    question: "Which national team are called “Baggy Greens”",
    a: "Pakistan",
    b: "Bangladesh",
    c: "South Africa",
    d: "Australia",
    correct: "d",
  },
  {
    question: "What was the margin of West Indies victory over Australia in the first (1975) World Cup final",
    a: "21 Run",
    b: "17 Run",
    c: "27 Run",
    d: "O7 Run",
    correct: "b",
  },
  {
    question: "How many minutes before play should the umpires take the field",
    a: "Six",
    b: "Ten",
    c: "Five",
    d: "Two",
    correct: "c",
  },
  {
    question: "Who is the first batsman to cross 10000 runs in Tests",
    a: "Sachin Tendulkar",
    b: "Rahul Dravid",
    c: "Sunil Gavaskar",
    d: "Mohammad Azharuddin",
    correct: "c",
  },
  {
    question: "Which national team is nicknamed “The Proteas” or “The Springboks”",
    a: "West Indies",
    b: "South Africa",
    c: "Australia",
    d: "England",
    correct: "b",
  },
  {
    question: "When and where did India play her first one day International",
    a: "In 1974 at Leeds, England",
    b: "In 1973 at Eden Gardens, India",
    c: "In 1974 at Green Park Stadium, India",
    d: "In 1974 at Wankhede Stadium, India",
    correct: "a",
  },
  {
    question: "What was the Kolkata Knight Riders highest total for 2017 season",
    a: "188/5",
    b: "187/6",
    c: "177/5",
    d: "187/5",
    correct: "d",
  },
  {
    question: "When was the Mumbai Indians club founded",
    a: "2009",
    b: "2008",
    c: "2010",
    d: "2007",
    correct: "b",
  },
  {
    question: "Who does the best batting average in a test career belong",
    a: "Steve Smith",
    b: "Virat Kohli",
    c: "Don Bradman",
    d: "Joe Root",
    correct: "c",
  },
  
  {
    question: "How many runs did Sachin Tendulkar was scored in his ODI debut",
    a: "15",
    b: "10",
    c: "01",
    d: "0",
    correct: "d",
  },
  {
    question: "Sourav Ganguly made his Test debut in 1996.How many runs did he score in the 1st innings of that match",
    a: "85",
    b: "101",
    c: "51",
    d: "131",
    correct: "d",
  },
  {
    question: "How many wickets Kapil Dev had taken in Test matches when he retired",
    a: "434",
    b: "404",
    c: "480",
    d: "435",
    correct: "a",
  },
  {
    question: "When did Sourav Ganguly made his ODI debut",
    a: "21 January 1992",
    b: "11 January 1992",
    c: "12 January 1992",
    d: "19 January 1992",
    correct: "b",
  },
  {
    question: "Who was the first Indian batsman to hit a century in a Test match",
    a: "Lala Amarnath Bharadwaj",
    b: "Kapil Dev",
    c: "Sunil Gavaskar",
    d: "Vijay Hazare ",
    correct: "a",
  },

];
